{% set name = "conda-which" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kelvinou01/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: aba98b3448c727b868db3a6294c8f661994454f2b6b3d8e2057ae1ad22a0a9e0

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}
    - conda
    - termcolor

test:
  imports:
    - conda_which
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check


about:
  home: https://github.com/kelvinou01/conda-which
  license: MIT
  license_file: LICENSE
  summary: Which package does this file belong to?

extra:
  recipe-maintainers:
    - kelvinou01
