{% set name = "conda-which" %}
{% set version = "0.2.1-rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kelvinou01/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8932a3ee31a5887b799b1d52d4ae37d59f0e84956751ba53928540e6d78685f0

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}
    - conda
    - termcolor

test:
  imports:
    - conda_which
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check


about:
  home: https://github.com/kelvinou01/conda-which
  license: MIT
  license_file: LICENSE
  summary: Which package does this file belong to?

extra:
  recipe-maintainers:
    - kelvinou01
