{% set name = "conda-which" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kelvinou01/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip

  run:
    - python >=3.8
    - conda
    - termcolor

test:
  imports:
    - conda_which
  requires:
    - pip
  commands:
    - pip check


about:
  home: https://github.com/kelvinou01/conda-which
  license: MIT
  license_file: LICENSE
  summary: Which package does this file belong to?

extra:
  recipe-maintainers:
    - kelvinou01
