{% set name = "conda-which" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kelvinou01/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4d5339af5f5fe04f41ee3f320610fb13fcc2e6d4359ff2ad939de60692ba6c59

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}
    - conda
    - termcolor

test:
  imports:
    - conda_which
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check


about:
  home: https://github.com/kelvinou01/conda-which
  license: MIT
  license_file: LICENSE
  summary: Which package does this file belong to?

extra:
  recipe-maintainers:
    - kelvinou01
